package realrender;

import org.lwjgl.input.Keyboard;

import net.minecraft.client.Minecraft;
import net.minecraft.client.entity.AbstractClientPlayer;
import net.minecraft.client.entity.EntityPlayerSP;
import net.minecraft.client.model.ModelPlayer;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.client.renderer.entity.RenderPlayer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.ResourceLocation;
import net.minecraft.world.World;
import net.minecraftforge.client.event.RenderHandEvent;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.client.registry.IRenderFactory;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent.Phase;
import net.minecraftforge.fml.common.registry.EntityRegistry;
import net.minecraftforge.fml.relauncher.Side;

@Mod.EventBusSubscriber(Side.CLIENT)
@Mod(modid = REN.MODID, name = REN.MODNAME, version = REN.MODVER)
public class REN {
	public static final String MODID="rfpr";
	public static final String MODNAME="Real First-Person Render";
	public static final String MODVER="9.0.0";	
	
	private static float bodyOffset;
	/**Array for modes.  First number is 3D arms, 
	 * 2nd number is visible body, and 3rd number is visible HUD.
	 */
	private static int[] modes;
	
	private static boolean customItemOverride;
	private static boolean wasF1DownLastTick;
	private static byte currentMode = 0;
	private static byte spawnDelay = 100;
	private static EntityPlayerDummy dummy;
	private static String[] overrideItems; 

	@EventHandler
	public void PreInit(FMLPreInitializationEvent event){
		this.initModMetadata(event);
		RenderingRegistry.registerEntityRenderingHandler(EntityPlayerDummy.class, new RENRenderingFactory(RenderPlayerDummy.class));
		Configuration config = new Configuration(event.getSuggestedConfigurationFile());
		config.load();
		overrideItems = config.get(Configuration.CATEGORY_GENERAL, "OverrideItems", new String[]{"map", "compass", "clock"}, "When these items are held, RFPR will temporally stop rendering.").getStringList();
		bodyOffset = (float) config.get(Configuration.CATEGORY_GENERAL, "RenderOffset", "0.35", "How far behind the player the body will render.").getDouble();
		modes = config.get(Configuration.CATEGORY_GENERAL, "Modes", new String[]{"111", "110", "011", "000", "001"}, "Mode IDs.  \nFirst number is whether to render arms in 3D or 2D mode.  \nSecond number is whether or not to render the body model.  \nThird number is whether or not to render the HUD.  \nAdd, delete, or change the order as you wish.  \nNOTE: Modes of type 1xx will NOT work with shaders!").getIntList();
		config.save();
	}
	
	@EventHandler
	public void Init(FMLInitializationEvent event){
		EntityRegistry.registerModEntity(new ResourceLocation(this.MODID, "PlayerDummy"), EntityPlayerDummy.class, "PlayerDummy", 0, MODID, 5, 100, false);
	}
	
	private void initModMetadata(FMLPreInitializationEvent event){
        ModMetadata meta = event.getModMetadata();
        meta.name = this.MODNAME;
        meta.description = "Small mod that adds in full-body rendering.";
        meta.authorList.clear();
        meta.authorList.add("don_bruce");
        
        meta.modId = this.MODID;
        meta.version = this.MODVER;
        meta.autogenerated = false;
	}
	
	@SubscribeEvent
	public static void on(TickEvent.ClientTickEvent event){
		if(event.phase.equals(Phase.START)){
			if(Keyboard.isKeyDown(Keyboard.KEY_F1)){
				if(!wasF1DownLastTick){
					if(currentMode == modes.length - 1){
						currentMode = 0;
					}else{
						++currentMode;
					}
				}
				wasF1DownLastTick = true;
			}else{
				wasF1DownLastTick = false;
			}
			Minecraft.getMinecraft().gameSettings.hideGUI = modes[currentMode]%10 != 1;
		}
		
		customItemOverride = false;
		EntityPlayer player = Minecraft.getMinecraft().player;
		if(player != null){
			if(player.inventory.getCurrentItem() != null){
				for(String itemName : overrideItems){
					if(itemName.equals(player.inventory.getCurrentItem().getUnlocalizedName().substring(5))){
						customItemOverride = true;
						break;
					}
				}
			}
		
			if(dummy == null){
			      if(spawnDelay == 0){
			    	  dummy = new EntityPlayerDummy(player.world);
			    	  dummy.setPositionAndRotation(player.posX, player.posY, player.posZ, player.rotationYaw, player.rotationPitch);
			    	  player.world.spawnEntity(dummy);
			      }else{
			        --spawnDelay;
			      }
			}else if(dummy.world.provider.getDimension() != player.world.provider.getDimension() || dummy.getDistanceSq(player) > 5 || dummy.lastTickUpdated < player.world.getTotalWorldTime() - 20){
				dummy.setDead();
				dummy = null;
				spawnDelay = 100;
			}
		}
	}
	
	@SubscribeEvent
	public static void on(RenderHandEvent event){
		event.setCanceled(modes[currentMode]/100 == 1 && !customItemOverride);
	}
	
	public static class EntityPlayerDummy extends Entity{
		public long lastTickUpdated;
		
		public EntityPlayerDummy(World world){
			super(world);
			this.ignoreFrustumCheck = true;
			this.setSize(0, 2);
			this.lastTickUpdated = world.getTotalWorldTime();
		}
		public void onUpdate(){
			EntityPlayer player = Minecraft.getMinecraft().player;
			dummy.setPositionAndRotation(player.posX, player.posY, player.posZ, player.rotationYaw, player.rotationPitch);
			this.lastTickUpdated = world.getTotalWorldTime();
		}
		protected void entityInit(){}
		protected void readEntityFromNBT(NBTTagCompound p_70037_1_){}
		protected void writeEntityToNBT(NBTTagCompound p_70014_1_){}
	};
	
	public static class RenderPlayerDummy extends Render{
		public RenderPlayerDummy(RenderManager renderManager){
			super(renderManager);
		}
		
		@Override
		public void doRender(Entity entity, double x, double y, double z, float yaw, float ticks){
			if(Minecraft.getMinecraft().gameSettings.thirdPersonView == 0 && modes[currentMode]%100 >= 10){
				EntityPlayerSP player = Minecraft.getMinecraft().player;
				if(player.isElytraFlying()){return;}
				Render<AbstractClientPlayer> render = (RenderPlayer) this.renderManager.<AbstractClientPlayer>getEntityRenderObject(player);
				RenderPlayer playerRenderer = (RenderPlayer)render;
				ModelPlayer playerModel = (ModelPlayer) playerRenderer.getMainModel();
				playerModel.bipedHead.isHidden = true;
				playerModel.bipedHeadwear.isHidden = true;
				
				ItemStack tempStackMain = player.inventory.getCurrentItem();
				ItemStack tempStackSecond = player.inventory.offHandInventory.get(0);
				if(modes[currentMode]/100 != 1 || (customItemOverride && modes[currentMode]%10 == 1)){
					player.inventory.removeStackFromSlot(player.inventory.currentItem);
					player.inventory.offHandInventory.set(0, ItemStack.EMPTY);
					playerModel.bipedLeftArm.isHidden = true;
					playerModel.bipedRightArm.isHidden = true;
					playerModel.bipedLeftArmwear.isHidden = true;
					playerModel.bipedRightArmwear.isHidden = true;
				}
				//Temporarily remove helmet prior to rendering.
				ItemStack helmetStack = player.inventory.armorInventory.get(3);
				player.inventory.armorInventory.set(3, ItemStack.EMPTY);
				if(player.isPlayerSleeping()){
					playerRenderer.doRender(player, player.posX - entity.posX + x, player.posY - entity.posY + y, player.posZ - entity.posZ + z, player.renderYawOffset, ticks);
				}else{
					double renderOffset = player.prevRenderYawOffset - (player.prevRenderYawOffset - player.renderYawOffset)*ticks;
					playerRenderer.doRender(player, player.posX - entity.posX + x + bodyOffset*Math.sin(Math.toRadians(renderOffset)), player.posY - entity.posY + y, player.posZ - entity.posZ + z - bodyOffset*Math.cos(Math.toRadians(renderOffset)), (float) renderOffset, ticks);
				}
				player.inventory.armorInventory.set(3, helmetStack);
				playerModel.bipedHead.isHidden = false;
				playerModel.bipedHeadwear.isHidden = false;
				if(modes[currentMode]/100 != 1 || (customItemOverride && modes[currentMode]%10 == 1)){
					player.inventory.setInventorySlotContents(player.inventory.currentItem, tempStackMain);
					player.inventory.offHandInventory.set(0, tempStackSecond);
					playerModel.bipedLeftArm.isHidden = false;
					playerModel.bipedRightArm.isHidden = false;
					playerModel.bipedLeftArmwear.isHidden = false;
					playerModel.bipedRightArmwear.isHidden = false;
				}
			}
		}

		@Override
		protected ResourceLocation getEntityTexture(Entity entity){
			return null;
		}
	};

	public class RENRenderingFactory implements IRenderFactory{
		private final Class<? extends Render> entityRender;
		public RENRenderingFactory(Class<? extends Render>  entityRender){
			this.entityRender = entityRender;
		}
		
		@Override
		public Render createRenderFor(RenderManager manager){
			try{
				return entityRender.getConstructor(RenderManager.class).newInstance(manager);
			}catch(Exception e){
				e.printStackTrace();
				return null;
			}
		}
	};
}
